config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_public#landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  resources :users, only: %i[index]
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  
         def self.from_omniauth(access_token)
          data = access_token.info
          user = User.where(email: data['email']).first
      
          # Uncomment the section below if you want users to be created if they don't exist
          unless user
              user = User.create(
                 email: data['email'],
                 password: Devise.friendly_token[0,20]
              )
          end
          user
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/static_public_controller.rb
class StaticPublicController < ApplicationController
  skip_before_action :authenticate_user!
  def landing_page
  end

  def privacy
  end

  def terms
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb:
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
  
        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    def index
        @users = User.all 
    end
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(name, path)
    content_tag(
      :li,
      class: "#{'active fw-bold' if current_page?(path)} nav-item",
    ) { link_to name, path, class: 'nav-link' }
  end
end

def deep_active_link_to(path)
  content_tag(
    :li,
    class: "#{'active fw-bold' if current_page?(path)} nav-item",
  ) do
    link_to path, class: 'nav-link' do
      yield
    end
  end
end

def deep_active_link_to_dropdown_item(path)
  content_tag(:li) do
    link_to path,
            class: "#{'active fw-bold' if current_page?(path)} dropdown-item" do
      yield
    end
  end
end

app/helpers/static_public_helper.rb
module StaticPublicHelper
end

app/views/layouts/_footer.html.erb
<div class="bg-light text-center">
    FOOTER
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="fas fa-flag"></i>
      Brand
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= deep_active_link_to root_path do %>
          <div class="fa fa-home"></div>
          Home
        <% end %>
        <%= deep_active_link_to users_path do %>
          <div class="fa fa-home"></div>
          Users
        <% end %>
         <%= deep_active_link_to privacy_path do %>
          <div class="fa fa-home"></div>
          Privacy
        <% end %>
         <%= deep_active_link_to terms_path do %>
          <div class="fa fa-home"></div>
          Terms
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item ">
              <%= link_to current_user.email, edit_user_registration_path %>
            
                <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
        
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= favicon_link_tag "legocity.png"%>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body >
    <%= render 'layouts/messages' %>
    <%= render 'layouts/header' %>
  
      <div class="container">
    <%= yield %>
    </div>


    
  </body>
   <footer>
     <%= render 'layouts/footer' %>
   </footer>
</html>

app/views/static_public/landing_page.html.erb
<h1>StaticPublic#landing_page</h1>
<p class="mt-5">Find me in app/views/static_public/landing_page.html.erb</p>
<i class="fa fa-diamond" aria-hidden="true"></i>
<i class="fa fa-telegram" aria-hidden="true"></i>

app/views/static_public/privacy.html.erb
<h1>StaticPublic#privacy</h1>
<p>Find me in app/views/static_public/privacy.html.erb</p>
<i class="far fa-address-book"></i>
<i class="fab fa-github"></i>

app/views/static_public/terms.html.erb
<h1>StaticPublic#terms</h1>
<p>Find me in app/views/static_public/terms.html.erb</p>

app/views/users/index.html.erb
 <% @users.each do |user|%>
    <%= user.email%>
    <br>
 <%end%>